port: 2408

grafana:
  url: "http://devops.ujing.online:3000"
  # 环境, 默认"test": 选参: test, production
  env: "production"

webhook: 
  type: "workweixin"
  url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key="
  # 消息类型, 默认"markdown"; 选参: text, markdown, image, news, file
  msgtype: "markdown"
  # 被@用户
  atuser: "suntao"
